services:
  - type: web
    name: ocean-digital-panel
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_ENV
        value: production
